### ISSUE TITLE
allow badger options to be specified

### ISSUE THREAD

**Issue by cameronbraid** [jpincas/tormenta#10]
Hi,

I would like to be able to configure badger options in a few cases

- Options.Truncate bool - needed if the badger log needs to be truncated
- Options.ValueLogLoadingMode - to specify options.FileIO to use less memory

Is this something you would consider exposing ?

**Comment by jpincas** [comment]
Definitely - it was something I actually had in the back of my mind. I'll get it done shortly.

Just a heads up - Tormenta is still quite unstable as I'm playing with the API a fair bit still.  At some point soon I'll try to move to a more formal release cycle, so that `master` can be somewhat stable at least.

**Comment by jpincas** [comment]
Done
